apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-icons-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-icons
  template:
    metadata:
      labels:
        app: social-icons
    spec:
      containers:
      - name: social-icons
        image: shivaamaroju/3d-social-icons:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: social-icons-service
spec:
  type: LoadBalancer
  selector:
    app: social-icons
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
